# Welcome to Numpy 

In [1]:
import numpy as np

In [2]:
myarr = np.array([3, 6, 32, 7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr = np.array([[3, 6, 32, 7]])

In [5]:
myarr[0, 1]

6

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.size

4

In [8]:
myarr.dtype

dtype('int32')

In [9]:
myarr[0, 1] = 45

In [10]:
myarr

array([[ 3, 45, 32,  7]])

In [11]:
la = np.array([[1, 2, 3], [4, 5, 6], [0, 9, 8]])

In [12]:
la

array([[1, 2, 3],
       [4, 5, 6],
       [0, 9, 8]])

In [13]:
la.dtype

dtype('int32')

In [14]:
la.size

9

In [15]:
la.shape

(3, 3)

In [16]:
np.array({23, 54})

array({54, 23}, dtype=object)

In [17]:
zeros = np.zeros((2, 5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.shape

(2, 5)

In [20]:
zeros.size

10

In [21]:
rng = np.arange(20)

In [22]:
import numpy as np

In [23]:
rg = np.arange(20)

In [24]:
rg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
lspace = np.linspace(1, 50, 50)

In [26]:
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [27]:
emp = np.empty((4, 6))

In [28]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        9.34609111e-307, 1.42417900e-306, 1.78019082e-306],
       [1.37961913e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 1.27946076e-307, 6.23037657e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        1.60221072e-306, 1.11261027e-306, 2.56761491e-312]])

In [29]:
emp_like = np.empty_like(lspace)

In [30]:
emp_like

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [31]:
ide = np.identity(25)

In [32]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 

In [33]:
ide.shape

(25, 25)

In [34]:
am = np.arange(99)

In [35]:
am

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
am.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
am

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
am = am.reshape(3, 33)

In [39]:
am

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
am = am.ravel()

In [41]:
am

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
am.shape

(99,)

In [43]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [44]:
ar = np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
sm = ar.sum(axis=0)

In [47]:
sm

array([12,  8,  9])

In [48]:
sm = ar.sum(axis=1)

In [49]:
sm

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
list(ar.flat)

[1, 2, 3, 4, 5, 6, 7, 1, 0]

In [52]:
ar.ndim

2

In [53]:
ar.nbytes

36

In [54]:
one = np.array([1, 3, 4, 634, 2])

In [55]:
one

array([  1,   3,   4, 634,   2])

In [56]:
one.argmax()

3

In [57]:
one.argmin()

0

In [58]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int32)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.argmin()


8

In [61]:
ar.argmin()

8

In [62]:
ar.argmax()

6

In [63]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int32)

In [64]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [67]:
ar.reshape((1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [68]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [84]:
ar2 = np.array([[1,(3,),4], [4, 3, 7], [6, 5, 9]])
ar = np.array([[1,3,4], [4, 3, 7], [6, 5, 9]])

c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [70]:
ar2

array([[1, 3, 4],
       [4, 3, 7],
       [6, 5, 9]])

In [71]:
ar + ar2

array([[ 2,  5,  7],
       [ 8,  8, 13],
       [13,  6,  9]])

In [72]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [73]:
ar.sum()

29

In [74]:
ar.min()

0

In [75]:
ar.max()

7

In [76]:
np.where(ar>2)

(array([0, 1, 1, 1, 2], dtype=int32), array([2, 0, 1, 2, 0], dtype=int32))

In [77]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [78]:
np.count_nonzero(ar)

8

In [79]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [86]:
art = np.array([[(1,), (2,)], [(3,), (4,)]])

In [87]:
art2 = np.array([[(1,), (2,)], [(3,), (4,)]])

In [89]:
art+art2

array([[[2],
        [4]],

       [[6],
        [8]]])